services:
  wholy-backend:
    build: ./my-medusa-store
    ports:
      - 7001:7001
      - 9000:9000
    environment:
      ADMIN_DASHBOARD_HOST: "0.0.0.0"
      ADMIN_DASHBOARD_PORT: "7001"

      HOST: "0.0.0.0"
      PORT: "9000"

      DATABASE_TYPE: "postgres"
      DATABASE_URL: ${DATABASE_URL}
      MEDUSA_ADMIN_ONBOARDING_TYPE: "nextjs"
      ADMIN_CORS: "http://localhost:7000,http://localhost:7001,0.0.0.0:7001"
      STORE_CORS: "http://localhost:3000,http://localhost:8000,http://localhost:7001"
      MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY: "my-medusa-store-storefront"

      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
      
    healthcheck:
      test: "curl --fail \"http://localhost:9000/store/ping\" || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s

    volumes:
      - backend-files:/app/uploads
  
  wholy-website:
    build: ./wholy-website
    ports:
      - 8000:8000
      - 3000:3000
    environment:
      NEXT_PUBLIC_SERVER_BACKEND_URL: "http://wholy-backend:9000"
      NEXT_PUBLIC_CLIENT_BACKEND_URL: "http://localhost:9000"
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      wholy-backend:
        condition: service_healthy

    

volumes:
  backend-files: