import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import "./styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(`CustomLog: Environment Variables:\n${JSON.stringify(process.env, null, 2)}`);

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        {/* <link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&display=swap" rel="stylesheet" /> */}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&display=block" rel="stylesheet" />
        
        <link href="/fonts/CabinetGrotesk-Regular.woff2" rel="preload" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link href="/fonts/CabinetGrotesk-Extrabold.woff2" rel="preload" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link href="/fonts/GloriaHallelujah-Regular.woff2" rel="preload" as="font" type="font/woff2" crossOrigin="anonymous" />
      </head>
      <body style={{position: "relative"}} className={inter.className}>{children}</body>
    </html>
  );
}